"""PQC type stubs — generated by Qryptive transformer."""
from dataclasses import dataclass


@dataclass(frozen=True)
class MLDSAPrivateKey:
    raw: bytes


@dataclass(frozen=True)
class MLDSAPublicKey:
    raw: bytes


@dataclass(frozen=True)
class MLKEMPrivateKey:
    raw: bytes


@dataclass(frozen=True)
class MLKEMPublicKey:
    raw: bytes
